### PR TITLE
Misc. (see desc.)

### PR DESCRIPTION
**Pull request by NicolasGraph**
Hi,
I should have create different pull requests, so tell me if you don't need all changes. 
- Moves Textpattern.tips in Resources (non official);
- Updates The Textpattern documentation link;
- Adds Textpattern GitHub repos as official resources;
- Adds GitHub in the networks list (under Community);
- Adds core and plugins developers lists (mainly for Forum profile and Github account
  links).

### CODE REVIEW

**Comment by drmonkeyninja** [comment]
Hi @NicolasGraph sorry it's taken me a while to take a look at this pull request. I'm not 100% convinced by the value of adding all the links to GitHub repositories. For example, I've deliberately excluded Txpmag.com in the past as the site has been dead for years so including it's repo seems pointless. Repo's for themes should perhaps be under a "Themes" heading.

I can see some value including the Core and Plugins developers though.

**Comment by NicolasGraph** [comment]
Thanks for the feedback; what do you think about the last changes?

**Comment by drmonkeyninja** [comment]
Those changes look good, unfortunately I appear to have broken things a bit for you with my recent changes (I'm having to update things to try and get the list approved for the official Awesome list). Could you fix the merge conflicts so that I can merge in your changes? Sorry.

**Comment by NicolasGraph** [comment]
No worry, I close this PR and open a new one with proper commits.

**Pull request closed without merging**
