### PR TITLE
Rvm css

### PR DESCRIPTION
**Pull request by juanjonavarro**

### CODE REVIEW

**Comment by drmonkeyninja** [comment]
Do you know if there is a GitHub repository for this plugin?

**Comment by juanjonavarro** [comment]
Unfortunately not :(

**Comment by drmonkeyninja** [comment]
That's ok. I'll add it anyway. Perhaps we can reach out to the developer and encourage them to add it to GitHub. :-)

**Comment by juanjonavarro** [comment]
Perfect. It's a shame a lot of plugins (mine included :smile: ) are not on github.

**Pull request merged**
