### PR TITLE
Replaces oui_dailymotion by oui_video

### PR DESCRIPTION
**Pull request by NicolasGraph**
oui_dailymotion is now deprecated.

### CODE REVIEW

**Comment by drmonkeyninja** [comment]
Thanks @NicolasGraph. I've updated the list with your pull request, but fixed the ordering of the plugins as they should be in alphabetical order.

How are you developing/compiling your oui_video plugin? Your repository has an interesting structure and looks more like how I'd like to develop. Is this something that has changed with Textpattern? I'm a little out of the loop I suspect.

**Comment by NicolasGraph** [comment]
Sorry, I thought that I had respected the alphabetical order…

I now use the Jukka's [MassPlugCompiler](https://github.com/gocom/MassPlugCompiler) and it is great! I discovered it thanks to Jakob. 
For oui_video, the structure is even better in the [dev branch](https://github.com/NicolasGraph/oui_video/tree/dev) (mainly in [src](https://github.com/NicolasGraph/oui_video/tree/dev/src)) and makes it easily extendable.

**Comment by drmonkeyninja** [comment]
Thanks @NicolasGraph I've never seen this before, it looks like just the thing I've been after. It's a shame that things like this aren't more _official_ and taken on by the [core Textpattern project](https://github.com/textpattern).

**Comment by NicolasGraph** [comment]
You're absolutely right @drmonkeyninja.
Most people maybe use [ied_plugin_composer](https://github.com/Bloke/ied_plugin_composer) to develop?

**Comment by NicolasGraph** [comment]
You could add [MassPlugCompiler](https://github.com/gocom/MassPlugCompiler) somewhere in this repo; it would be a first step to make it more _official_.

**Comment by drmonkeyninja** [comment]
@NicolasGraph I've added it to the list with commit 57d6403ca38c84bda65ee9bb8f134c103b9589d8. Thanks for the suggestion.

**Comment by NicolasGraph** [comment]
Great; have a good day!

**Pull request merged**
